sudo: required
services:
  - docker

before_install:
  - docker build -t miguelgz/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true miguelgz/docker-react-tutorial npm run test
