branch-defaults:
  master:
    environment: docker-react-tutorial-env
global:
  application_name: docker-react-tutorial
  default_platform: 64bit Amazon Linux 2015.03 v1.4.1 running Docker 1.6.0
  default_region: us-east-1
  sc: git