version: 2.1
executors:
  docker-image:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/miguelgz36/docker-react-tutorial/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: docker-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t miguelgz/circleci-demo-docker:$TAG -f Dockerfile.dev .
  test:
    executor: docker-image
    requires :
      - build
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker run -e CI=true miguelgz/circleci-demo-docker:$TAG npm run test        
workflows:
  my-custom-workflow:
    jobs:
      - build
      - test