version: 2.1
executors:
  docker-image:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/miguelgz36/docker-react-tutorial/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:
    executor: docker-image
    steps:
      - checkout
      - run: |
          docker build -t miguelgz/docker-react-tutorial -f Dockerfile.dev .
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name