version: 2.1
executors:
  docker-image:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/miguelgz36/docker-react-tutorial/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: docker-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          docker build -t miguelgz/circleci-demo-docker -f Dockerfile.dev .
      - run:
          name: Save image as tar
          command: |
            mkdir -p images
            docker image save -o "images/miguelgz_circleci-demo-docker" "miguelgz/circleci-demo-docker"
      - persist_to_workspace:
          root: .
          paths:
            - images          
  test:
    executor: docker-image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true    
      - run:
          name: Load image
          command: |
            docker image load < "images/miguelgz_circleci-demo-docker"    
      - run: |
          docker run -e CI=true miguelgz/circleci-demo-docker npm run test
  deploy:
      docker:
        - image: cimg/python:3.11.4
      steps:
        - checkout
        - run: pip3 --version
        - run:
            command: pip install python-docx
        - run:
            working_directory: /
            name: installing ebcli
            command: pip3 install awsebcli --upgrade --user   
        - run: eb --version
        - run:
            name: deploying with awsebcli
            command: eb deploy  docker-tutorial-front-end-$CIRCLE_BRANCH        
workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: aws-creds
          filters:
            branches:
              only:
                - master
          requires:
            - test