version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
executors:
  docker-image:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/miguelgz36/docker-react-tutorial/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: docker-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          docker build -t miguelgz/circleci-demo-docker -f Dockerfile.dev .
      - run:
          name: Save image as tar
          command: |
            mkdir -p images
            docker image save -o "images/miguelgz_circleci-demo-docker" "miguelgz/circleci-demo-docker"
      - persist_to_workspace:
          root: .
          paths:
            - images          
  test:
    executor: docker-image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true    
      - run:
          name: Load image
          command: |
            docker image load < "images/miguelgz_circleci-demo-docker"    
      - run: |
          docker run -e CI=true miguelgz/circleci-demo-docker npm run test
             
workflows:
  build-test-deploy:
    jobs:
      #- build
      #- test:
      #    requires:
      #      - build
      - eb/deploy:
          context: aws-creds
          environment-name: docker-react-tutorial-env
          filters:
            branches:
              only:
                - master
          platform-version: docker        
        #  requires:
        #    - test