version: 2.1
executors:
  docker-image:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/miguelgz36/docker-react-tutorial/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: docker-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          docker build -t miguelgz/circleci-demo-docker -f Dockerfile.dev .
  test:
    executor: docker-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          docker run miguelgz/circleci-demo-docker npm run test        
workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build