version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/miguelgz36/docker-react-tutorial/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # docker build -t miguelgz/docker-react-tutorial -f Dockerfile.dev .
  test:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # docker run -e CI=true miguelgz/docker-react-tutorial npm run test  
workflows:
  my-custom-workflow:
    jobs:
      - build
      - test:
          requires:
            - build

